### ISSUE TITLE
Support for M1 macs

### ISSUE THREAD

**Issue by seanturner026** [oktadev/terraform-provider-oktaasa#12]
As an m1 mac user, I am unable to `terraform init` this provider.

```
Error: Incompatible provider version

Provider registry.terraform.io/oktadeveloper/oktaasa v1.0.1 does not have a
package available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider
may have different platforms supported.
```

**Comment by sgal-dm** [comment]
@monde sorry for the cross-product tag, but you're really active in the Okta TF provider repo, and this one seems dead. Any chance you can nudge someone at Okta who owns the ASA TF provider to publish the darwin_arm64 package?

This issue appears to be resolved in code, but the package isn't published to the Terraform registry, pulling this repo and building locally outputs a darwin_arm64 package, but without standing up a private provider repository that doesn't do us any good.

**Comment by monde** [comment]
@sgal-dm @seanturner026 

I think this provider is superseded by https://registry.terraform.io/providers/okta/oktapam/latest

But I was able to build terraform-provider-oktaasa locally. I'm on OSX, this is what I did.

https://goreleaser.com/install/
https://goreleaser.com/quick-start/

```
$ cd /path/to/my/projects
$ git clone https://github.com/oktadev/terraform-provider-oktaasa.git
$ cd terraform-provider-oktaasa/

$ brew install goreleaser
$ goreleaser release --snapshot --rm-dist

# binaries built to dist/
$ file dist/terraform-provider-oktaasa_darwin_arm64/terraform-provider-oktaasa_v1.0.1-SNAPSHOT-7787387

dist/terraform-provider-oktaasa_darwin_arm64/terraform-provider-oktaasa_v1.0.1-SNAPSHOT-7787387: Mach-O 64-bit executable arm64

$ cp dist/terraform-provider-oktaasa_darwin_arm64/terraform-provider-oktaasa_v1.0.1-SNAPSHOT-7787387 \
  /path/to/my/local/bin
```

Then, I think you can do something like this in `${HOME}/.terraformrc`, see https://www.terraform.io/cli/config/config-file

```
provider_installation {
  dev_overrides {
    "oktadeveloper/oktaasa" = "/path/to/my/local/bin"
  }
  direct {}
}
```

Let me know if this gets you moving.

Also, I heard this at work "afaik, this has been superseded by an updated provider here: https://registry.terraform.io/providers/okta/oktapam/latest and https://github.com/okta/terraform-provider-oktapam"

**Comment by sgal-dm** [comment]
Looking over the documentation, I think you're right about the oktapam provider superceding this one, and even if you're not those instructions are definitely enough to get us going. Thanks @monde!

**Comment by seanturner026** [comment]
Cool, I think I can close this then. Happy to reopen if someone needs it opened.
